spring:
  application:
    name: oauth
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/oauth_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: ${SQL_INIT_MODE:never}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:9000}
